name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.1'

      - name: Run Tests
        run: |
          go install github.com/boumenot/gocover-cobertura@latest
          go test -v ./api/... ./pkg/... -coverprofile=coverage.txt -covermode count
          $(go env GOPATH)/bin/gocover-cobertura < coverage.txt > coverage.xml
          go tool cover -func=coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
